#### package config #######
package_name: salary_model

training_data_file: salary_train.csv
test_data_file: salary_test.csv
pipeline_name: salary_regression_model
pipeline_save_file: salary_regression_model_output
# to set the random seed
random_state: 0
# set train/test split
test_size: 0.2

#### Model config #####
target: Salary

features:
  - YearsExperience

numerical_vars_to_cast_to_float:
  - Salary
  - YearsExperience

fit_intercept: True


