on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: semantic syntax version of the package
        type: text

jobs:
   publish:
#     env:
#       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#       AWS_SECRETS_ACCESS_KEY: ${{ secrets.AWS_SECRETS_ACCESS_KEY }}
#       BUCKET_BASE_PATH: 'ml-model-packages/titanic-solution'
#       GEMFURY_PUSH_URL: ${{ secrets.GEMFURY_PUSH_URL }}


     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
       - name: set up Python 3.7
         uses: actions/setup-python@v4
         with:
            python-version: "3.7"

       - name: Fetch the data
         run: |
            curl https://www.openml.org/data/get_csv/16826755/phpMYEkMl --output ./classification_model/datasets/raw.csv
       - name: install tox
         run: pip install tox --user tox
       - name: Security gates
         run:
           tox -e checks

       - name: Test the model
         run: |
            tox
       - name: Install pypa/build
         run: |
            pip install build --user
       - name: Build a binary wheel and a source tarball
         run: >-
             python -m
             build
             --sdist
             --wheel
             --outdir dist/

       - name: Publish distribution 📦 to Test PyPI
         uses: pypa/gh-action-pypi-publish@release/v1
         with:
           password: ${{ secrets.TEST_PYPI_API_TOKEN }}
           repository-url: https://test.pypi.org/legacy/
           
         
